nvchecker:
  source: cmd
  cmd: bash -c 'dir=$(mktemp -d -t zapzap-git-XXXXXX); (cd $dir && git clone https://github.com/zapzap-linux/zapzap && cd zapzap && git describe --long --tags | sed "s/^foo-//;s/\([^-]*-g\)/r\1/;s/-/./g;s/^v//"); rm -rf $dir'
test: true
