nvchecker:
  regex: glassoFast_([\d.]+).tar.gz
  source: regex
  url: https://cran.r-project.org/web/packages/glassoFast/index.html
test: true
update_script: bin/update-pkgver --target _pkgver
oldver: 1.0.1
